//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandAuto.CLIENT {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ISEL.CLIENT", ConfigurationName="CLIENT.ClientContract")]
    public interface ClientContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISEL.CLIENT/ClientContract/submitProposal", ReplyAction="http://ISEL.CLIENT/ClientContract/submitProposalResponse")]
        void submitProposal(string stand, string proposal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientContractChannel : StandAuto.CLIENT.ClientContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientContractClient : System.ServiceModel.ClientBase<StandAuto.CLIENT.ClientContract>, StandAuto.CLIENT.ClientContract {
        
        public ClientContractClient() {
        }
        
        public ClientContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void submitProposal(string stand, string proposal) {
            base.Channel.submitProposal(stand, proposal);
        }
    }
}
