//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandAuto.Broker {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ISEL.BROKER.STAND", ConfigurationName="Broker.IBrokerStandService")]
    public interface IBrokerStandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISEL.BROKER.STAND/IBrokerStandService/registerStand", ReplyAction="http://ISEL.BROKER.STAND/IBrokerStandService/registerStandResponse")]
        void registerStand(string standEndpoint);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrokerStandServiceChannel : StandAuto.Broker.IBrokerStandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrokerStandServiceClient : System.ServiceModel.ClientBase<StandAuto.Broker.IBrokerStandService>, StandAuto.Broker.IBrokerStandService {
        
        public BrokerStandServiceClient() {
        }
        
        public BrokerStandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrokerStandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerStandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerStandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void registerStand(string standEndpoint) {
            base.Channel.registerStand(standEndpoint);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ISEL.BROKER.CLIENT", ConfigurationName="Broker.IBrokerClientService")]
    public interface IBrokerClientService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ISEL.BROKER.CLIENT/IBrokerClientService/submitQueryByBrand")]
        void submitQueryByBrand(string client, string brand);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ISEL.BROKER.CLIENT/IBrokerClientService/submitQueryByMinumumYearRegistrati" +
            "on")]
        void submitQueryByMinumumYearRegistration(string client, int yearRegistration);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ISEL.BROKER.CLIENT/IBrokerClientService/submitQueryByMaxPrice")]
        void submitQueryByMaxPrice(string client, int maxPrice);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrokerClientServiceChannel : StandAuto.Broker.IBrokerClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrokerClientServiceClient : System.ServiceModel.ClientBase<StandAuto.Broker.IBrokerClientService>, StandAuto.Broker.IBrokerClientService {
        
        public BrokerClientServiceClient() {
        }
        
        public BrokerClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrokerClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void submitQueryByBrand(string client, string brand) {
            base.Channel.submitQueryByBrand(client, brand);
        }
        
        public void submitQueryByMinumumYearRegistration(string client, int yearRegistration) {
            base.Channel.submitQueryByMinumumYearRegistration(client, yearRegistration);
        }
        
        public void submitQueryByMaxPrice(string client, int maxPrice) {
            base.Channel.submitQueryByMaxPrice(client, maxPrice);
        }
    }
}
